// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjovfujbfqwouopnupwb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdqb3ZmdWpiZnF3b3VvcG51cHdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE3MjAxNTYsImV4cCI6MjA4NzI5NjE1Nn0.asgYSNPgcR7Ql--t5fKEsBaRWnJz3ySrE7u2rJfoKPo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});